### ISSUE TITLE
CompatibilityVersion.Version_2_2

### ISSUE THREAD

**Issue by kakone** [stimulsoft/Samples-NET.Core-MVC-CSharp#5]
Hello,

I'm trying the "Edit Report in the Designer" sample. I noticed that if I set the target framework to .NET Core 2.2 and the compatibility version to 2.2 in the Startup.cs file : `services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);`
the designer can't run (there are some javascript errors : `Uncaught ReferenceError: StiMobileDesigner is not defined`).
If I set the compatibility version to 2.1, it works well.

**Comment by VladimirBLR** [comment]
Hello,

The problem has already been fixed, the update will be available in the next version. At the moment, you can manually set the value of the routes using the options of the viewer or designer:

```
Server =
{
    RouteTemplate = "rptview/Home/{action}"
},
```
